#ifndef DATAMODEL_HPP
#define DATAMODEL_HPP

enum class MenuScreen
{
    START_SCREEN,
    START_MEASURE_SCREEN,
    MEASURES_REGISTRY_SCREEN,
    SETTINGS_SCREEN,
    HELP_SCREEN,
    GENERAL_INFO_SCREEN,
    USER_MANUAL_SCREEN,

};

#endif // DATAMODEL_HPP
